### ISSUE TITLE
CDI 2 Timetable Missmatch

### ISSUE THREAD

**Issue by SkyDev125** [joanasesinando/gerador-horarios-ist#68]
**Describe the bug**
The Timeslots of the CDI 2 classes seem to be incorrect

**To Reproduce**
1. Go to https://fenix.tecnico.ulisboa.pt/disciplinas/Fis3/2023-2024/2-semestre/horario, check the calendar there.
2. Go to https://web.tecnico.ulisboa.pt/joanasesinando/gerador-horarios/ and check the timeslot for CDI 2

**Expected behavior**
Timetables to match

**Screenshots**
![image](https://github.com/joanasesinando/gerador-horarios-ist/assets/41944315/91c3e33b-0b3c-4aa6-8ffd-94b35ff1c6d3)
![image](https://github.com/joanasesinando/gerador-horarios-ist/assets/41944315/589e54ee-3c4b-4700-9d22-da7d74668ca4)

**Comment by joanasesinando** [comment]
Temporary mismatch in Fénix API.
Seems fixed!
